name: build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          pip install pip-licenses
        shell: bash
      - name: Build
        run: |
          pyinstaller --onefile onadaily.py
          ls -al
        shell: bash
      - name: Copy config file
        run: cp onadaily.yaml dist/
        shell: bash
      - name: Copy licenses
        run: |
         pip-licenses > dist/depend-licenses.txt
         cp LICENSE dist/LICENSE.txt
        shell: bash
      - name : Archiving
        run: |
          cd dist
          Compress-Archive .\* onadaily-windows-onefile.zip
        shell: powershell
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/onadaily-windows-onefile.zip
