name: build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
        shell: bash
      - name: Build
        run: |
          pyinstaller --onefile onadaily.py
          ls -al
        shell: bash
      - name: Copy config file
        run: cp onadaily.yaml dist/
        shell: bash
      - name : Archiving
        run: |
          cd dist
          Compress-Archive .\* onadaily-windows-onefile.zip
        shell: powershell
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: onadaily-windows.zip
