name: build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
      - name: copy config file
        run: |
          cp onadaily.yaml dist/windows/onadaily/
      - name: Archiving dist
        run: |
          (cd dist/windows/onadaily && zip -r onadaily-windows.zip *) > onadaily-windows.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: onadaily-windows.zip