name: build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          cache: 'pipenv'
      - name: Install pipenv and shell
        run: |
          pip install pipenv
          pipenv shell
      - name: Install dependencies
        run: |
          pipenv install
          pip install pyinstaller
          pip install pip-licenses
        shell: bash
      - name: Build onefile
        run: |
          pyinstaller --onefile main.py --name onadaily
          cp onadailyorigin.yaml dist/
          pip-licenses > dist/depend-licenses.txt
          cp LICENSE dist/LICENSE.txt
          Compress-Archive .\dist\* onadaily-windows-onefile.zip
          ls
        shell: powershell
      - name: Build
        run: |
          pyinstaller main.py --name onadaily
          cp onadailyorigin.yaml dist/onadaily/
          pip-licenses > dist/onadaily/depend-licenses.txt
          cp LICENSE dist/onadaily/LICENSE.txt
          Compress-Archive .\dist\onadaily\* onadaily-windows.zip
      - name: Release check
        uses: kaisugi/action-regex-match@v1.0.1
        id: regex
        with:
          text: ${{ github.ref }}
          regex: 'refs\/tags\/v\d+\.\d+\.\d+pre\d+'

      - name: Release pre-release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.regex.outputs.match != '' }}
        with:
          body: "onadaily-windows-onefile.zip 은 하나로 압축시킨 파일입니다. 바이러스로 오진될 수 있습니다. 이 경우엔 onadaily-windows.zip을 사용하세요.\n이 버전은 베타 버전입니다. 오류가 발생할 수 있습니다."
          files: |
            onadaily-windows-onefile.zip
            onadaily-windows.zip
          prerelease: true
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.regex.outputs.match == '' }}
        with:
          body: "onadaily-windows-onefile.zip 은 하나로 압축시킨 파일입니다. 바이러스로 오진될 수 있습니다. 이 경우엔 onadaily-windows.zip을 사용하세요."
          files: |
            onadaily-windows-onefile.zip
            onadaily-windows.zip
